# Generated by Django 5.2.5 on 2025-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0002_catagory_users_expense_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='goal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goal'),
        ),
    ]
