# Generated by Django 5.2.5 on 2025-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0004_alter_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=500, null=True, verbose_name='Password'),
        ),
    ]
