# Generated by Django 5.2.5 on 2025-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0006_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
