# Generated by Django 5.2.6 on 2025-09-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0007_alter_users_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catagory',
            table='Catagory',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='Expense',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
