# Generated by Django 5.2.6 on 2025-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0008_alter_catagory_table_alter_expense_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='goal',
            field=models.IntegerField(default=0, verbose_name='Goal'),
        ),
    ]
