# Generated by Django 5.2.6 on 2025-09-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0009_alter_users_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='goal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Goal'),
        ),
    ]
