# Generated by Django 5.2.6 on 2025-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0013_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
