# Generated by Django 5.2.6 on 2025-09-24 12:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0014_catagory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
