# Generated by Django 5.2.6 on 2025-09-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_buddy_app', '0015_alter_catagory_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='color',
        ),
    ]
